### ISSUE TITLE
Uncaught TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by ahmet** [codeship/atom-codeship-status#1]
Hi,

I've just installed the plugin, created .codeship.yml as described and re-opened Atom, but the following exception came up.

**Atom Version**: 0.169.0
**System**: Mac OS X 10.10.2
**Thrown From**: [codeship-status](https://github.com/codeship/atom-codeship-status) package, v0.1.1
### Stack Trace

Uncaught TypeError: Cannot read property 'match' of undefined

```
At /Users/ahmet/.atom/packages/codeship-status/lib/build-status-view.coffee:102

TypeError: Cannot read property 'match' of undefined
  at BuildStatusView.module.exports.BuildStatusView.repoStatus (/Users/ahmet/.atom/packages/codeship-status/lib/build-status-view.coffee:102:42)
  at ClientRequest.<anonymous> (/Users/ahmet/.atom/packages/codeship-status/lib/build-status-view.coffee:1:1)
  at ClientRequest.g (events.js:199:16)
  at ClientRequest.emit (events.js:107:17)
  at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:418:21)
  at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
  at TLSSocket.socketOnData (_http_client.js:309:20)
  at TLSSocket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:161:16)
  at TLSSocket.Readable.push (_stream_readable.js:125:10)
  at TCP.onread (net.js:522:20)

```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store",
      ".powrc",
      ".rspec",
      ".rvmrc",
      ".rubocop.yml",
      ".gitignore"
    ],
    "projectHome": "/Users/ahmet/Projects"
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.1.0
atom-lint, v0.20.1
codeship-status, v0.1.1
color, v0.5.0
editor-stats, v0.16.0
language-haml, v0.14.0
language-rspec, v0.2.1
packages, vundefined
tabs-to-spaces, v0.8.0
webbox-color, v0.5.4

# Dev
No dev packages
```

/cc @atom/core

**Comment by mlocher** [comment]
Ahoy @ahmet, 

the Atom extension is pretty much unmaintained since the last commit. I'll take a look at it this weekend and see that I get it working with the latest version of Atom again.

Thanks very much for the feedback!
